### ISSUE TITLE
Isn't AdBarker more of a prefix, not a host?

### ISSUE THREAD

**Issue by johnspurlock** [opawg/podcast-hosts#26]
AdBarker is currently listed in the [hosts file](https://github.com/opawg/podcast-hosts/blob/eb0d5018f6e2abaca4fefa3b7d4c450709129dec/src/hosts.json#L2335), but they appear to consist of a [prefix-based ad-insertion redirection service](https://adbarker.com/stream/asdf) to other underlying hosts.

Shouldn't they be over in the prefixes file instead?

**Comment by jamescridland** [comment]
They use prefixes to grab the original audio and insert ads into it (so the audio is hosted with them). I think therefore it's a host more than a prefix service, but should probably be in both, I reckon?

**Comment by jamescridland** [comment]
(I've added it into the prefixes too).

**Comment by johnspurlock** [comment]
Unclear to me if they're going to use a different prefix for podinch, which I guess would be pure analytics prefix according to this definition.  I have an email out to them, don't know of any shows that use them at the moment.

**Comment by johnspurlock** [comment]
Looking deeper at existing adbarker shows, it looks like they just 302 over to the source.  So perhaps their integration with the hosts means they actually modify the audio on the host, then just redirect for analytics?

If this is the case for all of them, seems like they would be pure analytics/prefix, less host

https://feeds.captivate.fm/enterprisenow/
460cb216-9b21-450e-af5c-e6b65cf8d61b
https://adbarker.com/stream/HPNFm8ghBRF6qASWj15ZEFkB/podcasts.captivate.fm/media/4fa612bf-8323-4947-a394-50554b063304/en-ep-191-podcast-final.mp3
302s to captivate -> https://podcasts.captivate.fm/media/4fa612bf-8323-4947-a394-50554b063304/en-ep-191-podcast-final.mp3

https://feeds.buzzsprout.com/1609978.rss
Buzzsprout-10006938
https://adbarker.com/stream/PX8A3DKx65WVexScwtpXHTx3/www.buzzsprout.com/1609978/10006938-episode-91-resident-retention-secrets-with-robert-ritzenthaler.mp3
302s to buzzsprout -> https://www.buzzsprout.com/1609978/10006938-episode-91-resident-retention-secrets-with-robert-ritzenthaler.mp3

**Comment by knagode** [comment]
Hey, @johnspurlock - we redirect to original audio if there are no ads for specific episode. This show has ads olmost in every episode: http://choosefi.libsyn.com/rss - that is why we redirect to audio file which is modified by us. 

E.g.: 
https://adbarker.com/stream/FUtw8akGsdUcxjeJU7HY5o1V/traffic.libsyn.com/secure/choosefi/366_Day_0_Self.mp3?dest-id=455223 [[ redirects to ]]-> https://cdn-a.adbarker.com/podcasts/FUtw8akGsdUcxjeJU7HY5o1V/episodes/6c2148632e03f03ec39ff60627ab43d2.mp3

We use this strategy on hosts that have signed Spotify Passtrough ammendment (e.g. Libsyn, Captivate ..). Very few hosting providers have this ammendment signed so we tried to use different strategy on Buzzsprout & Castos. We reauploaded modified audio file to their servers (otherwise ads would not be heard on Spotify). It would probably be WAY simpler if we would simply become a podcast hosting provider however I am not sure if it is good idea to become one - there are already so many competitors in this field .. But it it true that not many have DAI capabilities ...

**Comment by johnspurlock** [comment]
> But it it true that not many have DAI capabilities

This is so surprising to me in 2022

Thanks for the detail, the example terminating at your cdn-a.adbarker.com was really helpful to see.

I think I have enough info to distinguish in my reports on top hosts and trackers.

@jamescridland the AdBarker prefix url over in the prefixes db is not exactly right, I'll send a PR
